on:
  workflow_dispatch:
  inputs:
      flutter_version:
        description: 'Framework version'
        required: true
        default: '2.5.3'
      publish_artifacts:
        description: 'Publish artifacts'
        required: true
        default: 'true'
        
jobs:
 input_parameters:
  runs-on: ubuntu-latest
  
  steps:
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "credentials.json"
        json: ${{ secrets.CREDENTIALS_JSON }}
        dir: 'src/'
