name: inputParamater

on:
 workflow_dispatch:
   inputs:
      cloud_provider:
        description: 'Enter your Cloud Provider'
        required: true
        default: 'AWS'
      publish_artifacts:
        description: 'Publish artifacts'
        required: true
        default: 'true'

jobs:
  build-version:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Group of log lines
      run: |
        echo "::group::My title"
        echo 'text here' >> text1.txt
        pwd
        
    - name: Cloud
      run: |
        echo "the selected cloud provider is:=" ${{ github.event.inputs.flutter_version }} 
