name: inputParamater

on:
 workflow_dispatch:
   inputs:
      cloud_provider:
        description: 'Enter your Cloud Provider'
        required: true
        default: 'AWS'
      publish_artifacts:
        description: 'Publish artifacts'
        required: true
        default: 'true'

jobs:
  build-version:
    runs-on: ubuntu-latest

    steps:        
    - name: Cloud
      run: |
        echo "The selected cloud provider is: " ${{ github.event.inputs.cloud_provider }}
        echo "Publish Artifacts? is:=" ${{ github.event.inputs.publish_artifacts }} 
